---

    - name: Install FTP package
      yum:
              name: vsftpd
              state: present

    - name: copy config vsftpd
      template:
              src: vsftpd.conf.j2
              dest: /etc/vsftpd/vsftpd.conf

    - name: make directory upload
      shell:
              cmd: mkdir /var/ftp/pub/upload
    
    - name: Set SElinux  ftpd_anon_write
      seboolean:
              name: ftpd_anon_write
              state: yes
              persistent: yes

    - name: Set enable upload
      shell:
              cmd: chcon -t public_content_rw_t /var/ftp/pub/upload

    - name: Firewall settings
      firewalld:
              port: 20-21/tcp
              state: enabled
              permanent: yes
              immediate: yes

    - name: Firewall2 settings
      firewalld:
              port: 30000-31000/tcp
              state: enabled
              permanent: yes
              immediate: yes

    - name: chmod 777 upload
      shell: sudo chmod 777 /var/ftp/pub/upload

    - name: Start vsftpd
      shell: sudo systemctl start vsftpd

    - name: Enable vsftpd
      shell: sudo systemctl enable vsftpd

